# Generated by Django 5.2 on 2025-04-24 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'permissions': [('can_edit_comment', 'Can edit comment'), ('can_delete_comment', 'Can delete comment')]},
        ),
    ]
