# Generated by Django 5.2 on 2025-04-25 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_remove_post_liked_by_comment_modified_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='post',
            name='updated_at',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
