# Generated by Django 5.2 on 2025-04-29 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_post_liked_by_post_updated_at_delete_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='liked_by',
            new_name='likes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='updated_at',
        ),
    ]
